language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:


branches:
  except:
    - release
    - meta

notifications:
  email: false

script:
  - npm run build

after_success:
  # only run for master branch, we don't want to release PRs and other branches
#   - 'if [ "$TRAVIS_PULL_REQUEST" != "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then openssl aes-256-cbc -K $encrypted_d70c34fb3c42_key -iv $encrypted_d70c34fb3c42_iv -in travis-release-key.enc -out release_key -d; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bash ./travis_release.sh; fi'
