AWSTemplateFormatVersion: '2010-09-09'
Description: Service Worker Bucket

Parameters:
  BucketName:
    Description: Name of the service.
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html

  Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${BucketName}/*
          - Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::710688865869:root
            Action:
              - s3:ListBucketVersions
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource: !Sub arn:aws:s3:::${BucketName}
          - Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::710688865869:root
            Action:
              - s3:PutObjectAcl
              - s3:PutObject
            Resource: !Sub arn:aws:s3:::${BucketName}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
